parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\QwenService:
        arguments:
            $qwenApiKey: '%env(QWEN_API_KEY)%'