name: Hello World

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs:   
  hello:
    runs-on: ubuntu-24.04
    steps: 
      -name: Dire Bonjour
      run: echo "Hello, GitHub Actions!"
      -name: Se connecter à docker
      run: echo "$DOCKER_TOKEN" | docker_login -u "$DOCKER_USER" --password-stdin
      env:  
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN}}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}

      -name: Afficher les infos sur le contexte
      run: |
        echo "Repository: \${{ github.repository }}"
        echo "Branche: \${{ github.ref_name }}"
        echo "Auteur du commit: \${{ github.actor }}"


